version: '3.9'

services:
  
  tasktracker-projects:
    build:
      context: .
      dockerfile: Dockerfile
    

  
  tasktracker-users:
    build:
      context: ./TaskTracker.Users
      dockerfile: Dockerfile

  
  tasktracker-comments:
    build:
      context: ./TaskTracker.Comments
      dockerfile: Dockerfile

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"