name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root dependencies
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Main (Projects) Docker Image
        run: docker build -t tasktracker-projects .

      - name: Build Users Docker Image
        run: docker build -t tasktracker-users ./TaskTracker.Users

      - name: Build Comments Docker Image
        run: docker build -t tasktracker-comments ./TaskTracker.Comments

      - name: Docker Compose up
        run: docker compose up -d
